### ISSUE TITLE
Question: access from other containers

### ISSUE THREAD

**Issue by natcl** [misterpeee/balena-gps-ntpsecd#1]
This might sound like a silly question but would this stack provide accurate time to other containers running on the PI ?
I have a python application that needs to run on the pi and needs very precise time, would running it alongside this stack make the accurate time available to that container ?

Thanks !

**Comment by misterpeee** [comment]
Yes it should - the docker container for NTP runs in privileged mode and sets the clock for the the host OS, which in turn should be synchronised in any other containers.

**Comment by natcl** [comment]
Awesome, thanks a lot !
