### ISSUE TITLE
RPi 5 uart enable

### ISSUE THREAD

**Issue by kanokc** [misterpeee/balena-gps-ntpsecd#2]
On Raspberry Pi 5, to enable uart, at `BALENA_HOST_CONFIG_dtoverlay`, value "pi3-miniuart-bt" overlay is needed to change to "disable-bt" instead.

also "uart0" is needed to be added at Define `DT parameters for the default overlay`

**Comment by misterpeee** [comment]
Thanks for the info - Sadly i dont have a pi5, but ive updated the documentation based on your comments
